version: '2'

services:
  stratis:
    restart: always
    image: ckotte/stratis:2.0
    build:
        context: .
        dockerfile: Dockerfile
    container_name: stratis
    hostname: stratis
    ports:
      - '16174:16174'
    volumes:
      - /share/Container/stratis:/var/lib/stratis
    labels:
      local.skynet.description: "Stratis wallet"
      local.skynet.service: "stratis"
